version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # This will map two-ways locally and within the container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"