---
name: Checks
on:
  push: [main]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login into Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Run code linting
        run: docker-compose run --rm app sh -c "flake8"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

